#cloud-config
users:
  - name: root
    groups: sudo
    shell: /bin/bash
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    ssh_authorized_keys: ${ssh_public_key}
package_update: true
package_upgrade: false
packages:
  - nano
  - telnet

runcmd:
  - if hostname | grep -q "^nginx-"; then apt-get update && apt-get install -y nginx; fi
